Add a default for the node language version
renovatebot/pre-commit-hooks pull request #2628
Opened 2024-12-05 12:13 UTC by hofbi

Closes #2460

This avoids that pre-commit picks the latest node version available that might not be supported by renovate. Users can still override this if they want.

2024-12-05 12:32 UTC, jonesbusy commented
What about 

```
language_version: lts
```

It will ensure to stay on LTS instead of unsupported active version

2024-12-05 13:04 UTC, hofbi commented
@jonesbusy did not know that this feature existed. Do you know that this works? Do you have any example/documentation where this is mentioned?

2024-12-05 13:14 UTC, viceice requested changes
needs updated renovate config as mentioned in issue.

is this a fixed version or can we use a range? will that version automatically downloaded?

2024-12-05 13:16 UTC, jonesbusy commented
https://pre-commit.com/#overriding-language-version

The `language_version` is passed directly to the underlying tool. In that case `nodeenv`

I've just tested 

```shell
nodeenv --node=lts .test
 * Install prebuilt node (22.12.0) ..... done.
```

2024-12-05 13:36 UTC, hofbi commented on .pre-commit-hooks.yaml
> +  language_version: 22.12.0
```suggestion
  language_version: lts
```

2024-12-05 13:37 UTC, hofbi commented
Changed to `lts`.

@viceice what would have to be changed in the renovate config?

2024-12-09 21:20 UTC, viceice commented
does it support setting the major version only? because renovate sometimes doesn't support the newest lts for some time.

2024-12-10 03:52 UTC, jonesbusy commented
Apparently not

I tried without success

```
nodeenv --node=22.x .test
nodeenv --node=22 .test
```

2024-12-10 09:51 UTC, hofbi commented
Being said that you don't always support the latest LTS version, we might want to explicitly specify the node version to be used. This way, you can explicitly define what should be used and is supported.

If this becomes to much manual effort, maybe renovate can autoupdate this as well. WDYT @viceice.

2025-01-13 17:07 UTC, hofbi commented
Kind reminder @viceice

2025-05-06 08:53 UTC, viceice approved these changes

2025-05-06 08:55 UTC, merged